// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAKNuxoWvokjgo110DwlsaHcUxOIR1uHI',
    appId: '1:31357043846:web:706421c6a92ac5c7eebd07',
    messagingSenderId: '31357043846',
    projectId: 'ebooks-2023',
    authDomain: 'ebooks-2023.firebaseapp.com',
    storageBucket: 'ebooks-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkK-paD8aN8yOH_v1geAGEe9oSD8hnOIE',
    appId: '1:31357043846:android:bb9e644f9c57a28eeebd07',
    messagingSenderId: '31357043846',
    projectId: 'ebooks-2023',
    storageBucket: 'ebooks-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAT12aLnT361EG1qHfsF9KjrbSE0TuJEw',
    appId: '1:31357043846:ios:e45ba8bf5c860e34eebd07',
    messagingSenderId: '31357043846',
    projectId: 'ebooks-2023',
    storageBucket: 'ebooks-2023.appspot.com',
    iosClientId: '31357043846-9kpr2e96g2ja6tjisofnnnuo9h13d17h.apps.googleusercontent.com',
    iosBundleId: 'com.ebooks.ebooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAT12aLnT361EG1qHfsF9KjrbSE0TuJEw',
    appId: '1:31357043846:ios:e45ba8bf5c860e34eebd07',
    messagingSenderId: '31357043846',
    projectId: 'ebooks-2023',
    storageBucket: 'ebooks-2023.appspot.com',
    iosClientId: '31357043846-9kpr2e96g2ja6tjisofnnnuo9h13d17h.apps.googleusercontent.com',
    iosBundleId: 'com.ebooks.ebooks',
  );
}
